language: node_js
node_js:
  - 'lts/*'

before script:
  - npm install -g yarn bower gulp
after script:
  - yarn install && bower install
after success:
  - gulp build
  
notifications:
  email:
    on_failure: always
    on_success: never
