version: '2.1'
orbs:
  node: circleci/node@4.5.1
jobs:
  build:
    executor: 
       name: node/default
       tag: 'lts'
    steps:
      - checkout
      - node/install:
          lts: true
          install-yarn: true
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn build
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master
