name: Deploy to Surge.sh

on: push

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to nicholasadamou.com
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'nicholasadamou.com'
          project: 'build/'
          login: ${{ secrets.SURGE_LOGIN }}
          token: ${{ secrets.SURGE_TOKEN }}
